config/routes.rb
Closes #23
```
resources :podcasts, only: [:index, :show ]
resources :episodes, only: [:show] do
resources :reviews, only: [:create]
resources :favorites, only: [:create]
end
get 'recommended', to: 'episodes#recommended'
resources :reviews, only: [:index, :edit, :update, :destroy]
resources :favorites, only: [:index, :update, :destroy]
```
=> Add the relevant routes to the app

app/models/episode.rb, app/models/podcast.rb, app/models/review.rb, app/models/user.rb, db/seeds.rb
=> Connects foreign keys

app/controllers/episodes_controller.rb, test/controllers/episodes_controller_test.rb
This PR add the show controller. Closes #11
=> Add the show controller

app/controllers/reviews_controller.rb, test/controllers/reviews_controller_test.rb
=> adds reviews controller

app/controllers/favorites_controller.rb, db/migrate/20201124175405_add_default_value_for_finished_to_favorites.rb, db/schema.rb, test/controllers/favorites_controller_test.rb
Closes #14 
Set a default value for the finished column.
Add the #create action for the Favorites controller.
=> Add favorites controller #create and set default for finished

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_login_form.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_navbar.html.erb
Some form styling on log-in and sign-up. 
No brand colour, and needs to be centre aligned on computer.
=> log in styling

app/controllers/podcasts_controller.rb, app/views/podcasts/show.html.erb, test/controllers/podcasts_controller_test.rb
Closes #21 
Setup a simple controller for the show page. We also create a basic show view to test that everything is working.
=> Setup Podcast controller #show

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_login_form.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/pages_controller.rb, app/views/layouts/home.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
closes #4 
Basic layout for now. 
Note I also changed the bootstrap colour 'success' for a trial as you can see how cards are coloured. Looks terrible imo but thought i'd start toying with some colours for the brand
=> Home page nav bar

app/controllers/favorites_controller.rb, app/controllers/reviews_controller.rb, app/views/episodes/_review_form.html.erb, app/views/episodes/show.html.erb
Finished episode view with:
- Title
- Description
- Average rating
- Reviews
Closes #12
=> Episode view

app/assets/stylesheets/components/_cards.scss, app/views/layouts/home.html.erb, app/views/pages/home.html.erb
- Added the links
- Added some helper classes
- Added footer to homepage
Closes #8
=> Add links and correct data on homepage cards

app/views/layouts/application.html.erb, app/views/pages/home.html.erb
=> Makes footer sticky and renders it on home page

app/controllers/reviews_controller.rb, app/views/reviews/index.html.erb
- Added a controller to show all the reviews belonging to a specific user
- Create a basic index view for this
Closes #26 
Closes #27
=> Add review controller and basic index page

app/controllers/episodes_controller.rb, app/controllers/podcasts_controller.rb, app/controllers/reviews_controller.rb, app/views/pages/home.html.erb
User can view podcasts and episodes without being logged in 
User needs to log in to leave a review & add an episode to their favorites
Closes #18
=> Adds authentication with devise

app/models/review.rb, app/views/episodes/show.html.erb, app/views/pages/home.html.erb
- Added  `after_save` method to reviews to update the episode's average rating
- Tested in the view to make sure it worked 😄 
Closes #56
=> Create average rating for episode

app/javascript/packs/application.js, app/javascript/plugins/init_sweetalert.js, app/views/episodes/show.html.erb, package.json, yarn.lock
- Added sweet alert to 'Add to Favourites' button on episode show
- Added logic behind button so user can only add an episode once + the button changes to remove from favorites once added 
Closes #47
=> Favorites alert

app/controllers/reviews_controller.rb, app/views/reviews/edit.html.erb, app/views/reviews/index.html.erb, config/routes.rb
**Edit a review & delete a review** 
**My reviews**
**Edit bottom review**
**Updated review captured**
**Deleted that review**
=> Review controller edit update

app/controllers/pages_controller.rb, app/views/pages/home.html.erb
- Fetch all episodes with a 4 or 5 star rating and show them ordered by highest rating on the homepage (limited to 6 episodes)
Closes #7
=> Show highest rated episodes on the homepage

app/controllers/episodes_controller.rb, app/controllers/favorites_controller.rb, app/views/episodes/show.html.erb
This makes the button to remove a favourite on the show page (the one that @b-lauren added) work!
Closes #67
=> Add remove favorite functionality to show page

app/assets/stylesheets/components/_navbar.scss, app/views/reviews/edit.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_navbar_home.html.erb
Changed drop down links from both navbars w/ better ux on cursor hover
**From Homepage --** 
Links to Favorites --
**Links to My Reviews --**
=> Dropdown links

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/views/episodes/show.html.erb, db/seeds.rb
Basic styling on episode show page
Closes #49 
BEFORE WE MERGE WE CAN"T LOSE SWEET ALERT FAVORITE BUTTON - might need to resolve conflicts
=> Adds styling to episode show page

app/controllers/episodes_controller.rb, app/views/episodes/show.html.erb
Show a button to edit your review and hide the form if the user has already submitted a review.
Closes #75
=> Allow only one review per episode

app/controllers/favorites_controller.rb, app/views/favorites/index.html.erb
=> Show finished and unfinished favourites

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_search_form.html.erb
closes #51 
**Sign up**
**Login**
=> log ins tidy + search bar aligned

app/assets/stylesheets/components/_cards.scss, app/views/podcasts/index.html.erb, app/views/podcasts/show.html.erb
=> podcasts index done, but not show

.gitignore, Gemfile, Gemfile.lock, app/models/podcast.rb, config/environments/development.rb, config/storage.yml, db/migrate/20201126153239_create_active_storage_tables.active_storage.rb, db/schema.rb
=> Enable artwork

db/seeds-original-backup.rb, db/seeds.rb
The mocks database has been seeded and is responding ok
=> Mock data seed

app/assets/stylesheets/config/_fonts.scss
=> fonts changed

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/config/_fonts.scss, app/views/reviews/index.html.erb
Not finished but better than before
=> Reviews styling

app/views/episodes/show.html.erb, app/views/podcasts/show.html.erb, config/storage.yml
Merge this to fix the image meta tags
=> Hot fix meta tag

app/views/episodes/show.html.erb, app/views/podcasts/index.html.erb
=> Add images for podcasts

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/views/reviews/index.html.erb
=> made buttons scss file and added buttons

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_search_bar.scss, app/assets/stylesheets/components/_sound_waves.scss, app/assets/stylesheets/config/_colors.scss, app/javascript/packs/application.js, app/views/pages/home.html.erb, app/views/podcasts/index.html.erb, app/views/shared/_navbar_home.html.erb, app/views/shared/_search_form.html.erb
- changed search bar 
- made search bar align in center of nav bar
- added sound waves animation
- color nav bar on scroll with JS
- added banner to podcasts index page
=> More frontend changes

app/controllers/favorites_controller.rb, app/javascript/packs/application.js, app/views/episodes/show.html.erb, app/views/pages/home.html.erb
Closes #89 
This took me way longer than it should have, but you can now add and remove favourites from the homepage.
=> Add remove button on homepage

app/assets/stylesheets/components/_footer.scss
changed footer to black and text to white
=> changed footer to black

app/assets/stylesheets/components/_animation.scss, app/assets/stylesheets/components/_review_cards.scss, app/views/reviews/index.html.erb
killed the text decoration on the buttons
made the episode title into a link
=> changed links as Rebecca suggested

app/assets/stylesheets/components/_banner.scss, app/views/podcasts/index.html.erb
I just centered the text and gave it some margin etc
No background colour so it's the same as the page
=> changed banner

app/views/episodes/show.html.erb
Added the Spotify player.
Closes #94
=> Add player to Episode show

app/assets/stylesheets/components/_homepage_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/views/pages/home.html.erb, app/views/shared/_background_colors.html.erb, db/schema.rb
- made navbar white on scroll
- commented out background colours
- small tweaks to home page cards
Closes #148
=> Navbar white on scroll

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_margin.scss, app/assets/stylesheets/config/_fonts.scss, app/views/podcasts/index.html.erb, app/views/reviews/index.html.erb, app/views/shared/_footer.html.erb
done a couple of pages so far:
=> Css uniformity

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_homepage_cards.scss, app/views/pages/home.html.erb
- More styling to home page cards 
- different button colours for add to faves + delete 
- changed button opacity on hover
=> Style home page cards

app/views/favorites/index.html.erb
=> added banner on favourites

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_search_bar.scss, app/views/pages/home.html.erb, app/views/shared/_search_form.html.erb
=> spacing between search on homepage

app/views/shared/_navbar.html.erb
we can now style color of nav to be different on podcast index and podcast show :) 
<% if params[:controller] == "podcasts" && params[:action] == "index" %>
<% color = "#F8A33E" %>
<% elsif params[:controller] == "podcasts" && params[:action] == "show" %>
<% color = "#FEC864" %>
Closes #173
=> Add to if statement for nav bar

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_review_cards.scss, app/assets/stylesheets/components/_share_buttons.scss, app/assets/stylesheets/pages/_episode_show.scss, app/assets/stylesheets/pages/_show.scss, app/views/episodes/_review_form.html.erb, app/views/episodes/show.html.erb, app/views/shared/_share_buttons.html.erb
=> Style episode show page

app/assets/stylesheets/components/_animation.scss, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_homepage_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_review_cards.scss, app/assets/stylesheets/components/_stars.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_episode_show.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_podcast_show.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/episodes/show.html.erb, app/views/pages/home.html.erb, app/views/podcasts/show.html.erb, app/views/reviews/index.html.erb
=> Working way through list

app/assets/stylesheets/pages/_episode_show.scss
Small change to add some margin to the player.
I unfortunately couldn't change the color since Spotify seems to randomly generate the class.
Closes #180
=> Add margin to player

app/assets/stylesheets/components/_buttons.scss, app/views/podcasts/show.html.erb
=> Add favorite buttons and style text

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_episode_show.scss, app/views/episodes/_review_form.html.erb, app/views/episodes/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb
=> style of review cards on episode show

app/views/layouts/application.html.erb, app/views/shared/_share_buttons.html.erb
Small change to move the JS script tag into the head.
Hopefully this solves some of the problems 🤞 
Closes #192
=> Add js for share links to the header

app/controllers/pages_controller.rb
Show 10 random episodes to be used for the homepage scrolling cards.
Closes #193
=> Get 10 random episodes

app/assets/stylesheets/components/_animation.scss
changed to 40 seconds from 30 seconds and added more margin right so that it doesn't cover the heart icon when it moves up
=> slowed down and more margin right

app/assets/stylesheets/pages/_episode_show.scss, app/javascript/plugins/init_sweetalert.js, app/views/episodes/show.html.erb
- Fixed sweet alert on home page buttons 
- Removed weird scroll on episode show 
- Added link on episode show
=> Fix sweet alert

app/assets/stylesheets/pages/_favorites.scss, app/views/favorites/index.html.erb
=> favorite-nightmare-style

app/models/review.rb
Tiny change to fix the review delete function 😄
=> Allow reviews to be deleted

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/pages/_episode_show.scss, app/assets/stylesheets/pages/_favorites.scss, app/assets/stylesheets/pages/_podcast_show.scss, app/views/favorites/index.html.erb, app/views/pages/home.html.erb, app/views/podcasts/index.html.erb, app/views/podcasts/show.html.erb, app/views/reviews/index.html.erb
1) Changed colour of delete button on reviews index so delete and edit are different colours
2) Center text inside banner on reviews & favorites pages
3) Changed font weight of title on podcast show page cards
=> small style changes

app/assets/stylesheets/pages/_episode_show.scss, app/views/episodes/show.html.erb
Changed colour of buttons on episode show - remove & add are different now
=> Changed color of buttons on ep show
